<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function pokemon_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    case 'help.page.pokemon':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Pokemon module') . '</p>';

      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function pokemon_theme($existing, $type, $theme, $path)
{
  return [
    'pokemon_pokemon_count'   => [
      'variables' => [
        'count' => 0,
      ],
    ],
    'pokemon_pokemon_list'    => [
      'variables' => [
        'pokemons' => [],
        'pager'    => null,
      ],
    ],
    'pokemon_pokemon_details' => [
      'variables' => [
        'pokemon' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function pokemon_preprocess_pager(&$variables)
{
  // Nothing to do if there is only one page.
  $element = $variables['pager']['#element'];
  /** @var \Drupal\Core\Pager\PagerManagerInterface $pager_manager */
  $pager_manager = \Drupal::service('pager.manager');
  $pager         = $pager_manager->getPager($element);

  // Nothing to do if there is no pager.
  if (!isset($pager)) {
    return;
  }

 /* // Nothing to do if there is only one page.
  if ($pager->getTotalPages() <= 1) {
    return;
  }

  foreach ($variables['items']['pages'] as $index => &$pager_item) {
    $pager_item['attributes']->addClass('use-ajax');
  }
  unset($pager_item);

  foreach (['first', 'previous', 'next', 'last'] as $special_pager_item) {
    if (isset($variables['items'][$special_pager_item])) {
      $variables['items'][$special_pager_item]['attributes']->addClass('use-ajax');
    }
  }*/
}
